name: Test, lint and fix code style

on: ["push", "pull_request"]

jobs:
  test:
    name: Run tests with PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php-version: [7.3, 7.4, 8.0, 8.1, 8.2, 8.3, 8.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: composer-cache-${{ matrix.php }}-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Dependencies installation
        run: composer update --no-interaction --prefer-dist

      - name: Run PHPUnit
        run: composer test

  lint-and-fix:
    name: Lint code and fix code style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: composer-cache-${{ hashFiles('composer.json') }}

      - name: Dependencies installation
        run: composer update --no-interaction --prefer-dist

      - name: Run PHPStan
        run: composer stan

      - name: Run PHP CS Fixer
        run: composer cs:fix

      - name: Commit code style fixes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: fix code style"

  spelling:
    name: 文A Typos check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Search for misspellings
        uses: crate-ci/typos@master
